### ISSUE TITLE
External storage support

### ISSUE THREAD

**Issue by Scapy47** [Acclorite/book-story#106]
**Please, follow _all_ of these checks (Issues that do not will be canceled):**
- [x] This feature is not implemented and does not have opened/closed Issues.
- [x] I propose ONLY one feature at a time. One feature - one Issue.
- [x] I use English. This repository's language is English.
- [x] I properly filled the template below(not necessarily all parts, but at least first two).
- [x] I did not use any placeholder such as [Feature] or [Bug] in the title of the Issue.

**Why you want this feature to be implemented? Please describe.**

I have a SD card and a pen-drive that is filed with books. And I want to use that with your app

**Describe the feature you'd like to be implemented**

There should be option in setting where user can select which directory app will use to source books from using Android file/folder selection screen (sorry if it's wrong terminology I am from JavaScript ecosystem)

**Additional context**

I was looking for E-PUB reader for long time I found your app today. I like your app but I store my books in separate storage device so I can't use it for now

**Comment by Acclorite** [comment]
**Duplicate** of #78. **Please**, check all marks.
