### ISSUE TITLE
Error while adding books [.pdf]

### ISSUE THREAD

**Issue by TISupe** [Acclorite/book-story#107]
- Could not add these books because of error in Browse Screen
- App says file are empty when its not

![SmartSelect_20241019_060720_Book's Story](https://github.com/user-attachments/assets/fb2ee054-72e2-44f4-a11c-fa9b401de511)

**Comment by Acclorite** [comment]
The problem is in PDF text parsing method. Currently, only English and some other languages can be parsed. I had enough problems with PDF, so I will change it to display as is.

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by TISupe** [comment]
> to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html) maybe this will solve your problem.

get a life shit scum

**Comment by Acclorite** [comment]
Deleted.

**Comment by Acclorite** [comment]
Follow #117
