### ISSUE TITLE
Allow editing of book's name and cover image

### ISSUE THREAD

**Issue by wxnnvs** [Acclorite/book-story#108]
**Please, follow _all_ of these checks (Issues that do not will be canceled):**
- [x] This feature is not implemented and does not have opened/closed Issues.
- [x] I propose ONLY one feature at a time. One feature - one Issue.
- [x] I use English. This repository's language is English.
- [x] I properly filled the template below(not necessarily all parts, but at least first two).
- [x] I did not use any placeholder such as [Feature] or [Bug] in the title of the Issue.

**Why you want this feature to be implemented? Please describe.**

Some of my books show no cover image or have long titles, wich I want to customize.
When loading the book it said i could change some things later on, although i haven't found a way to do so.

**Describe the feature you'd like to be implemented**

When long pressing a book I would like to be able to edit it's metadata:
- Name
- Author
- Cover image
- Publication date
- ...

**Describe alternatives you've considered**

Manually editing the source file or finding another one.

**Additional context**

![Screenshot_20241102-144542-338.png](https://github.com/user-attachments/assets/2431e76c-2d60-43aa-8ca7-192079fed027)

Edit: This might be more of a bug actually

**Comment by Acclorite** [comment]
Just hold down the cover or title.. Please, read Help screen.

**Comment by wxnnvs** [comment]
damn i am sorry

**Comment by wxnnvs** [comment]
thx though
