### ISSUE TITLE
Editor de EPUB

### ISSUE THREAD

**Issue by Jose14** [Acclorite/book-story#110]
**Please, follow _all_ of these checks (Issues that do not will be canceled):**
- [ ] This feature is not implemented and does not have opened/closed Issues.
- [ ] I propose ONLY one feature at a time. One feature - one Issue.
- [ ] I use English. This repository's language is English.
- [ ] I properly filled the template below(not necessarily all parts, but at least first two).
- [ ] I did not use any placeholder such as [Feature] or [Bug] in the title of the Issue.

**Why you want this feature to be implemented? Please describe.**

**Describe the feature you'd like to be implemented**

**Describe alternatives you've considered**

**Additional context**

**Comment by Acclorite** [comment]
Zero checks, no description, title is not in English.
