### ISSUE TITLE
Advanced dictionary feature with apps like Chatgpt, Claude, etc.

### ISSUE THREAD

**Issue by nNoidea** [Acclorite/book-story#114]
**Please, follow _all_ of these checks (Issues that do not will be canceled):**
- [x] This feature is not implemented and does not have opened/closed Issues.
- [x] I propose ONLY one feature at a time. One feature - one Issue.
- [x] I use English. This repository's language is English.
- [x] I properly filled the template below(not necessarily all parts, but at least first two).
- [x] I did not use any placeholder such as [Feature] or [Bug] in the title of the Issue.

**Why you want this feature to be implemented? Please describe.**

When selecting a text, it is possible under the share option to directly paste it into apps such as ChatGPT, Claude etc. Most of the time these apps can explain the meaning of these words much better if you provide context.

**Describe the feature you'd like to be implemented**

In the settings the user first selects a dictionary provider. When the user selects apps such as ChatGPT or Claude, extra features apply.

Now assume the user has selected ChatGPT.

Basically while reading the user selects a word, next to options such as "copy" pops up the dictionary option, when clicked on this the app shares 1 paragraph (or sentence) up and 1 paragraph down from the current position of the selected text. And basically gives/shares the following prompt with the app:

```
Define the following word, in this context: {selected word}

Text:
{1 paragraph above}
{text paragraph}
{1 paragraph under}
```
ChatGPT will than most probably give a much more comprehensible answer to the user about the word's definition.

**Describe alternatives you've considered**

Allow us a button that automatically copies the wanted prompt to clipboard, so we can paste it quickly to apps such as Gemini, which can be quickly accessed through gestures.

**Additional context**

In another reading app called ReadEra, they allow users to use a dictionary with a browser where the user can use text interpolation for the url. This way, we can basically do stuff like
```
https://www.google.com/search?q=define%3A+{text}
```
to directly use the search engine as a dictionary.

**Comment by Acclorite** [comment]
Not possible with the current selection library in Jetpack Compose.

**Comment by immortal-forest** [comment]
How about giving this a try?

https://github.com/yamin8000/freeDictionaryApp

It works well with the reader. And it's just 3 MB.

![Screenshot_2024-11-19-00-58-58-03_195602553d1912bdbc06c97ae2c6cd69.jpg](https://github.com/user-attachments/assets/9d41ae6c-d5c7-416b-80a0-1f319b2282cf)

**Comment by nNoidea** [comment]
> How about giving this a try?
> 
> https://github.com/yamin8000/freeDictionaryApp
> 
> It works well with the reader. And it's just 3 MB.
> 
> ![Screenshot_2024-11-19-00-58-58-03_195602553d1912bdbc06c97ae2c6cd69.jpg](https://private-user-images.githubusercontent.com/95863983/387355984-9d41ae6c-d5c7-416b-80a0-1f319b2282cf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMzE0ODMsIm5iZiI6MTczMjAzMTE4MywicGF0aCI6Ii85NTg2Mzk4My8zODczNTU5ODQtOWQ0MWFlNmMtZDVjNy00MTZiLTgwYTAtMWYzMTliMjI4MmNmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDE1NDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYzJhNDUzNzlkNmQzNzY1MTQyOWMyYTk3Yzg3YjZlNTg4ODc1NjczYTk5MzhjNjRiODE1YTY4NTg5MGI4OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CJdHGjM3KOQDUHo0zCzcWFOlL8zA0EkfuFB3thlhXWY)

Already tried that app, but it does not advanced enough to provide a definition for everything. Some words do not exist and some words are not recognized when used in their plural or alternative forms.

Maybe I should open a feature request on that project tho :laughing:
