### ISSUE TITLE
Why is it loading?

### ISSUE THREAD

**Issue by Raffa064** [Acclorite/book-story#116]
I don't know what exactly is the app doing while loading, but it takes too long, that appears it's freezed...

I've used some tools to open it's internal files, and I can guess that it is trying to extract document text for show it on that "mobile display" (like some apps names it), but I don't think it need to be done as it is.

I suggest to open the documents normally, as a pdf reader, and use this "text only" display just as a option.

If you really want to use this text only display, might be better to generate it on demand, in backgroud while user is reading, not while adding the book.

**Comment by Acclorite** [comment]
It parses text, parsing while you are reading would create more problems like calculating progress or scrolling using slider. 

Showing PDFs directly, without text-only is planned and I bet I answered this one hundred times already. Other file formats still **will be** parsed, as it adds more flexibility for me.

Please, **do not ask questions** in Issues. There is Discussions tab.
