### ISSUE TITLE
[Duplicate] No access to external storage

### ISSUE THREAD

**Issue by inktveer** [Acclorite/book-story#124]
**Describe the bug**
The app has to access to files stored on external storage, such as a micro SD card. 

**To Reproduce**
1. Insert MicroSD card with epub, zip or pdf files, or any other file the app supports
2. Download the app and grant all storage access
3. Refresh the Browse view 
4. Observe the absence of the files on the external storage

**Expected behavior**
The files on the SD card show up in the Browse section so they can be imported into the reading view. The app detects the files on the external storage. 

**Device Info (please complete the following information):**
 - Device: Samsung Galaxy S9+
 - Android Version: 13
 - Version of the app: v1.4.0

**Comment by Acclorite** [comment]
Not a bug. Duplicate of #78.

**Comment by inktveer** [comment]
I see, then I will close the issue. I hope this will be added soon.
