### ISSUE TITLE
.fb2 files support

### ISSUE THREAD

**Issue by yonoff** [Acclorite/book-story#2]
Hi,

It would be great if you could add support for .fb2 files.

**Comment by Acclorite** [comment]
**Added** in [6e70901](https://github.com/Acclorite/book-story/commit/6e70901429a3a0c62b5d44dcfa82d5641a157467).
Please wait for the next release to have it. This file format still requires a lot of testing, parsing problems may exist (as I basically tested other file formats for months). 

If you found serious issue with parsing, please create another issue, send a book with the parsing issue and where exactly it happened. Some books for some reason don't want to be added, but they also don't want to be opened with the text editor (which I use for structure checking).

Known problems:
- Same as with ".pdf", there are problems with line breaking. I still did not find universal solution for that, therefore some line may be cut incorrectly (or more correctly, not preserved). Although it should work pretty much okay, all lines must be readable and correct.
