### ISSUE TITLE
Pdf books

### ISSUE THREAD

**Issue by digitaldynastyjohn** [Acclorite/book-story#24]
**Books story** is an awesome app
I think that books in tge **PDF** format like "Outliers by Malcolm Gladwell" and other no starch press programming books that i have should not be displayed in text form.

Some of these books have useful stuff like 
> charts
> diagrams
> tables
> images

Overall, the app is good for novels.
So I'd love it if the pdfs were  _**displayed normally**_ or the user could decide if they want it to be displayed normally or not.

**Comment by Acclorite** [comment]
This is not possible, at least with current Reader system. Basically, this app is intended to extract all the text from the books, not display it as is(for several reasons). Also, PDF extractor is really ugly and I have to use workarounds to get it working.. Just to get text extracted.

It may seem like an interesting idea, but I won't let your hopes up, as this feature probably will never be implemented(this way).

Although, there may be a bit other implementation, that could work and I already have that in my TODO, which could solve your problem, but it is a different approach and still on concept stage.

Thanks for suggestion.

**Comment by Acclorite** [comment]
Canceling, as this will conflict with other implementation.
If you have more ideas, please feel free to create new Issues, thanks♥

**Comment by digitaldynastyjohn** [comment]
Ok then, thank you dor ckearing this out.
Overall **I love the app** for reading text based PDFs like Wikipedia.

**Comment by digitaldynastyjohn** [comment]
Ok then, thank you for clearing this out.
Overall **I love the app** for reading text based PDFs like Wikipedia.
