### ISSUE TITLE
display text in vertical writing.

### ISSUE THREAD

**Issue by Kdroidwin** [Acclorite/book-story#27]
Sentences in Japanese are written in vertical writing from right to left.

**Comment by Acclorite** [comment]
Hm, this is a complicated question as I use prebuilt composables to display text and I have no access to change them directly. I have no skills in Japanese, so cannot verify that too. Also, I am not sure how that would be displayed if I understand your problem right.

You have limited width, but practically unlimited height, that's the problem with displaying text vertically.
