### ISSUE TITLE
Provide Text Alignment

### ISSUE THREAD

**Issue by mystic-man-rhino** [Acclorite/book-story#28]
Basic Text Alignments like. 

* Left Align
* Right Align
* Justify

**Comment by Acclorite** [comment]
Never thought of that, but if you want that, why not? Probably will not take more than a hour to do anyway.

**Comment by mystic-man-rhino** [comment]
Just reminding again.

**Comment by Acclorite** [comment]
**Added in 1cf5188.**

You can choose between **Start**, **Justify**, **Center** and **End** alignments.
Please wait for the next release, to see this feature in the app.
