### ISSUE TITLE
Support for .mobi format

### ISSUE THREAD

**Issue by goddaneel** [Acclorite/book-story#29]

**Comment by Acclorite** [comment]
Already in my TODO, if no issues occur, will be implemented.

**Comment by Acclorite** [comment]
Sadly issues occurred.
There is no library to parse MOBI files on Android, meaning the only way is to manually do that, but even with that I ran into multiple problems with parsing it.
Frozen and canceled until there is a library to parse it or I find a good way to do that manually.

**Comment by goddaneel** [comment]
I have been using this project before, but it has actually stopped maintenance

https://gitlab.com/axet/android-book-reader

It can read .mobi files simply, but I don’t know if it can be used as a reference.

**Comment by Darkrai9x** [comment]
Can you try using the following two libraries:

https://github.com/bfabiszewski/libmobi
Use JNI, convert MOBI to EPUB for reading.

https://github.com/gedoor/legado/tree/master/app/src/main/java/io/legado/app/lib/mobi
This lib parse and read the content directly from the MOBI format.
