### ISSUE TITLE
Missing Images 

### ISSUE THREAD

**Issue by mystic-man-rhino** [Acclorite/book-story#30]
Missing Image resources in the imported epub books.

**Comment by Acclorite** [comment]
This is not my issue, but parser's. I get the image from metadata, if it is not present there, then I cannot get it either.

**Comment by Acclorite** [comment]
P.s. If you mean images inside the book, then it is intended.

**Comment by Acclorite** [comment]
This issue is long closed and outdated. Please, check more recent one #69
