### ISSUE TITLE
Error when adding this epub

### ISSUE THREAD

**Issue by IsraelMarqs** [Acclorite/book-story#32]
[Robinson Crusoé - Daniel Defoe.zip](https://github.com/user-attachments/files/16570054/Robinson.Crusoe.-.Daniel.Defoe.zip)

The message that appears is:
![Screenshot_20240810_111423_Book's Story](https://github.com/user-attachments/assets/b7916ed1-8372-46eb-a9f8-5e5793acac75)

**Comment by Acclorite** [comment]
Thank you for report. Will try to fix!

**Comment by Acclorite** [comment]
**Will fix.**
You can track progress in corresponding issue(#34).

**Comment by Acclorite** [comment]
Resolved in #42.
Please wait for the next release.
