### ISSUE TITLE
Provide arch specific apk

### ISSUE THREAD

**Issue by n-ce** [Acclorite/book-story#33]
I'm a arm64 user and I don't want the app installation to carry the baggage of the rest of the ISA's my device won't support. Besides it's always a good exercise to provide them all separately.

**Comment by Acclorite** [comment]
Just tested it.
The next release will greatly decrease APK size(150% reduction). There is no difference in size between universal and any other versions of APK at this point, therefore, I don't see any reasons to include architecture specific APK, at least for now.

Thanks for suggestion.
