### ISSUE TITLE
Add Scroll bar

### ISSUE THREAD

**Issue by shuvashish76** [Acclorite/book-story#45]
**Why you want this feature to be implemented? Please describe.**
Adding scroll bar would allow you to know how long the vertical screen is with respect to current screen, also helps to drag & jump screen quickly.
Add it to reader screen, library, history, browse.. everywhere (only when scroll is necessary) because when we need scrolling better to scroll with a scroll bar :)

**Describe alternatives you've considered**
Have a look on these libraries
- https://github.com/zhanghai/AndroidFastScroll
- https://github.com/reddit/IndicatorFastScroll
- https://github.com/nanihadesuka/LazyColumnScrollbar

**Comment by Acclorite** [comment]
Thank you for suggestion.

Looks interesting and I don't see minuses on implementing this (if no issues occur).

**Comment by Acclorite** [comment]
Sadly there are issues with implementing this.

Thanks for referencing [this](https://github.com/nanihadesuka/LazyColumnScrollbar) library, it really works great, but there is one issue — it does not work with LazyListState in ViewModel, which is used in History, Browse and Reader. This basically means no scrollbar on those screens.

I still feel like it is better to have at least that, scrollbar will still be available on most of the screens.

**Comment by Acclorite** [comment]
Reconsidered my approach, **partly implemented**.
Fixed most issues, added scrollbar to non-primary screens, such as Settings, Help, About.
Although, it is not "primary" scrollbar, but semi-transparent secondary, which cannot be used for scrolling.

**Comment by shuvashish76** [comment]
> it is not "primary" scrollbar, but semi-transparent secondary, which cannot be used for scrolling.

So basically it's a "view bar" which case is: only to see the total screen highest in relation to current screen?

**Comment by Acclorite** [comment]
Easier to show haha
![Scrollbar.png](https://github.com/user-attachments/assets/056692e9-ef61-4761-994c-53fb34fb4eb7)
