### ISSUE TITLE
Improve/Add text selection toolbar actions in Reader

### ISSUE THREAD

**Issue by shuvashish76** [Acclorite/book-story#46]
**Describe the feature you'd like to be implemented**
Add option to show context menu actions when you perform text selection, which is better UX than current double click to send actions via intent.

**Describe alternatives you've considered**
For example when I select text in browser it gives options to copy, share, select all, actions from installed apps e.g. [Aard2](https://f-droid.org/packages/com.ichi2.anki/), [Translate You,](https://f-droid.org/packages/com.bnyro.translate/), [Tasks.org](https://f-droid.org/packages/org.tasks/), [AnkiDroid](https://f-droid.org/packages/com.ichi2.anki/) etc..

![Screenshot_2024-08-13_12-45-08_1](https://github.com/user-attachments/assets/5ee6ebae-7202-4ff8-8cef-72294ced1d35)

**Additional context**
https://developer.android.com/training/package-visibility/use-cases#custom-text-selection-actions

### Task list

- [x] Improve Dictionary text selection toolbar option.
- [x] Add new options to text selection toolbar.

**Comment by Acclorite** [comment]
> Add option to show context menu actions when you perform text selection, which is better UX than current double click to send actions via intent.

Personal preference. I prefer double click much more. Also, if you select text, you already see custom actions, e.g Translate or Dictionary, what's wrong with that?

**Comment by shuvashish76** [comment]
> Also, if you select text, you already see custom actions, e.g Translate or Dictionary, what's wrong with that?

https://github.com/user-attachments/assets/b87c4c38-20aa-4908-8fe0-542540cbe8e1

As you can see 1. Dictionary: redirects to browser only _(other app you see is AM's interceptor)_ 2. Translate: redirects to all other apps which is kind misleading 3. Missing share option as I shown in the screenshot of my 1st comment.

The current workaround works not a major issue but it's not perfect either.

**Comment by Acclorite** [comment]
> Dictionary: redirects to browser only, missing the Aard2 dictionary app (other app you see is AM's interceptor)

Can try to also target dictionaries, thanks.

> Translate: redirects to all other relevant installed apps, the title of this context menu is kinda misleading

What is misleading? It does what it says.

> Missing share option as I shown in the screenshot of my 1st comment

Actually I should be able to add share option, thanks.

> The current workaround works not a major issue but it's not perfect either. Adding all apps directly to the context menu would be nice.

I think it's already an achievement to be able to do that. I spent over week on this thing and that's all I could do.

**Comment by shuvashish76** [comment]
> What is misleading? It does what it says.

"Translate", but it tries to open dictionary, tasks, flashcard and all kind of apps...

> I think it's already an achievement to be able to do that. I spent over week on this thing and that's all I could do.

I agree 👍🏿, just need some improvements...maybe in future _if possible_. Low priority feature request. I appreciate your time & energy you're put in for this feature :D

**Comment by Acclorite** [comment]
> "Translate", but it tries to open dictionary, tasks, flashcard and all kind of apps...

Because it opens any app that processes text. There is no intent category "Translator", I either specify translators by myself, or go with all apps that can process text. It shouldn't be an issue after you selected desired app, so don't see it as misleading, it's all in your hands after all.

**Comment by Acclorite** [comment]
**Resolved in 3fdc289 and a830be1.**
Please wait for the next release.

Your notice about Translate action redirects to dictionary apps gave me a hint on how to target actual dictionary apps with Dictionary option.

- **Added Share option.**
- **Added Web Search option.**
- **Now Dictionary redirects to dictionary apps, if there are none, redirects to [good dictionary website](https://www.onelook.com/).**

As both Translate and Dictionary use same Intent, as a workaround you now have to choose an app to redirect to each time. (except double click translation)
