### ISSUE TITLE
 Add ability to set book colors according to selected dynamic (monet) color palette

### ISSUE THREAD

**Issue by zx8418** [Acclorite/book-story#53]
Maybe alternate default preset or a toggle in appearance settings?

**Comment by Acclorite** [comment]
I don't see any problems with replacing default color preset with current theme's background and font color.
Can you describe in details? Is taking colors from your color scheme at the moment of color preset creation (without changing it dynamically after) what you want?

**Comment by Acclorite** [comment]
**Implemented.** Please wait for the next release.

**How it works?**
When you add new color preset, it gets colors from your current theme.
