### ISSUE TITLE
Syncing with Kavita

### ISSUE THREAD

**Issue by H-e-n-r-i** [Acclorite/book-story#63]
I love the look and feel of the reader, and I would like to be able to read from my remote library from Kavita instead of needing to download all the ebooks onto my device.

It would be great if it could load the book from the Kavita instance as well as sync progress with it.

**Comment by Acclorite** [comment]
> could load the book from the Kavita instance as well as sync progress with it

Maaaaaybe it will be implemented, but not in the near future, if ever. My current focus is to provide best Reader experience by extending Reader customization and functionality.

I think I gave clear answer in #40.
