### ISSUE TITLE
AO3 EPUBS

### ISSUE THREAD

**Issue by sEatLad** [Acclorite/book-story#66]
Good day, 

**Describe the bug**
I tried using the app for reading books from the website [AO3](https://archiveofourown.org/) I have run in to some issues with the way the app shows the epubs I have downloaded.
1.  At 0% it opens the book at a random chapter if the book has multiple chapters.
2. If is a single chapter book , at 0% , it open the books with "The Afterwords" and the "End Notes" in other words in open the book with the final author's notes and words , and it ends the book with what should be the beginning. (I use other epub readers and this has never being an issue so I reckon it must be bug of some sort - I love your app UI so I hope to use your app as main driver)

**To Reproduce**
Steps to reproduce the behavior for multi chapter book Example:
1.Go to this [book](https://archiveofourown.org/works/23548405?view_full_work=true)
2. Click on 'Download' you will shown a selection of formats select EPUB
3. Open it in the app
4. Add 'What's Your Name?' to the Library from the browser tab. 
5. Find 'What's Your Name?' in the Library tab, press play.
6. You will see when you that it does not show what chapter is showing which is an issue when this one book has 51 chapters and the formatting of the writing in the book is not the way it should be either (I use Librera FD epub reader as a reference)

 
Steps to reproduce the behavior for single chapter book:
1. Go to this [book](https://archiveofourown.org/works/56233693) 
2. Click on 'Download' you will shown a selection of formats select EPUB
3. Open it in the app
4. Add 'Last Words' to the Library from the browser tab.
5. Find 'Last Words' in the Library tab, press play.
6. Showing "Afterword" and "End Notes" that should be at the end. Towards the end of the book , as shown in the app, the "Posted originally..." onward should be at the begging of the book not at the end (again my reference for how it should look like is the website itself and the app Librera FD which is my current epub reader)

**Expected behavior**
In Librera FD and I tried with other Epub Apps as well just to see, the epubs I get from AO3 work and look exactly like they do on the website. The links work and the formatting (the order in which the words and chapter order appear) is as expected just like on the website. 

**Screenshots (optional)**
I am open to providing screenshots I don't know if necessary but do let me know.
I included a screenshot to find the download bottom, just in case. 
![image](https://github.com/user-attachments/assets/3ac4d425-5715-48f9-9192-0e2d65480289)

**Device Info (please complete the following information):**
 - Device: Redmi Note 8
 - Android Version: 14
 - Version of the app v1.2.0

I hope this helps.

**Comment by Acclorite** [comment]
Thank you for report. Just for the future, it is recommended to use [book-parser](https://github.com/Acclorite/book-story/blob/master/.github/ISSUE_TEMPLATE/book-parser-issue.md) Issue template.

> At 0% it opens the book at a random chapter if the book has multiple chapters.

What **exactly** do you mean by that? Does it open the book at random scroll index, or is this parser issue? I mean, do you see "Start" item which shows title and "Happy reading!" phrase?

> If is a single chapter book , at 0% , it open the books with "The Afterwords" and the "End Notes" in other words in open the book with the final author's notes and words , and it ends the book with what should be the beginning.

Just downloaded "Last words", it shows up correctly, main text, then "Afterwords". Can you provide screenshots?

> You will see when you that it does not show what chapter is showing which is an issue when this one book has 51 chapters and the formatting of the writing in the book is not the way it should be either (I use Librera FD epub reader as a reference)

Well, not related to EPUB itself, the app does not have chapters as of now, but I do plan on adding them.
_See: #17_

> formatting of the writing in the book is not the way it should be either

I get EPUBs in their "natural" order, basically if author does some weird line cutting, which may not be visible in html, it will here. Really not sure how to make all EPUBs work and at the same time format them all good..

Here is an example:

```
  <span>There he is, staring back at you. Tom Riddle. He’s harder to recognise these days, but </span>
  <em class="calibre9">
    <span>you</span>
  </em>
```

It breaks the line, which results in "you" to be on another line. I can provide much more examples, but they all are similar - manual line breaking. I will once more reconsider my EPUB parser implementation, hope will find something that can fix these issues.

Also, make sure you use the latest app version, as it seems you have weird issues with parser, did you update the book's text if it was added before **Release v1.2.0**, which improved parsers? You can check that [here](https://github.com/Acclorite/book-story/releases/tag/v1.2.0) in **"How to update book's text after parser update"**.

**Comment by Acclorite** [comment]
**Resolved most of the problems:**
- At 0% it opens the book at a random chapter if the book has multiple chapters. - Fixed by properly sorting chapters.
- If is a single chapter book , at 0% , it open the books with "The Afterwords" and the "End Notes" in other words in open the book with the final author's notes and words , and it ends the book with what should be the beginning. - Still sorting, even if the book has "one" chapter, it is probably separated into multiple files in EPUB, fixed.
- You will see when you that it does not show what chapter is showing which is an issue when this one book has 51 chapters. - Yes, implemented.
- The formatting of the writing in the book is not the way it should be either. - I understand this issue, but sadly could not really fix that, the issue is still with inconsistent HTML formatting, solving his particular issue will probably break some of books entirely.
