### ISSUE TITLE
Reader Improvement

### ISSUE THREAD

**Issue by Acclorite** [Acclorite/book-story#70]
Various Reader enhancements to improve user experience.

### Task list (may extend)
- [x] #17 
- [x] #66 
- [x] #61
- [ ] #13
- [x] #74 
- [x] #72

**Comment by pluseach** [comment]
Would it be possible to implement a Material You reader, or at least have the color scheme follow the system/app themes?

**Comment by Acclorite** [comment]
> Would it be possible to implement a Material You reader, or at least have the color scheme follow the system/app themes?

Are you sure you got it right? When you add new color preset it sets colors according to MaterialYou theme. As for UI, it does follow Material3 guidelines as far as I can say.

**Comment by pluseach** [comment]
> Are you sure you got it right? When you add new color preset it sets colors according to MaterialYou theme. As for UI, it does follow Material3 guidelines as far as I can say.

It seems I didn't explain that very well, my apologies. What I meant was that the reader menu, when you're reading the book, the color preset doesn't match the theme of the material you.

**Comment by Acclorite** [comment]
> Maybe adding color preset buttons like 'AMOLED' or 'Dark' would help users avoid confusion?

I'll think about ways to do it more user-friendly, thanks.

**Comment by Acclorite** [comment]
Moved progress to [Reader Improvement milestone](https://github.com/Acclorite/book-story/milestone/1).
Moved discussion to #87.
