### ISSUE TITLE
OPDS Support

### ISSUE THREAD

**Issue by dgcampbe** [Acclorite/book-story#71]
**Why you want this feature to be implemented? Please describe.**
The ability to easy download ebooks in the ebook reader is extremely convient and a great user experience instead of having the exit the reader app and use a web browser to download an ebook to read.

**Describe the feature you'd like to be implemented**
Add OPDS catalogs, search/browse added catalogs, download from catalogs, etc.

**Describe alternatives you've considered**
The feature would be extremely convient for me. KOReader currently supports this, but the UI in unintuitive to me (I prefer Material You such as in this app). I am caught between having features or a UI I personally find enjoyable to use.

**Additional context**
This is a nice-to-have, but not strictly necessary, feauture along with similar features such as Calibre and Wallabag support (also features of KOReader).

Thanks!

**Comment by Acclorite** [comment]
**For your information #19 and #40.**

**This is large feature.
The app does not have a focus on online, so implementation is questionable.**

I want to focus on improving your reading experience. I know, it may be more convenient to download books within the app, but the main part and focus is to create the app rich of features for **reading**.
