### ISSUE TITLE
Import/Export Functionality for the Apps Database (settings, book status, reading progress, etc.)

### ISSUE THREAD

**Issue by ghost** [Acclorite/book-story#75]
**"Why do you want this feature implemented? Please describe.**
It would make it easier to transfer your  "Book's Story" data from one device to another.

**Describe the feature you'd like to be implemented**
Import/Export functionality for the app's database (settings, book status, reading progress, etc.)

**Describe alternatives you've considered**
Synchronization via services like Nextcloud

**Comment by Acclorite** [comment]
Follow #23
