### ISSUE TITLE
Custom brightness in Reader

### ISSUE THREAD

**Issue by Acclorite** [Acclorite/book-story#82]
**Why you want this feature to be implemented? Please describe.**
User may want to use different brightness for reading.

**Describe the feature you'd like to be implemented**
Slider/Switch to set custom brightness.

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Acclorite** [comment]
Added in 628f10f4e782b19f49af95f3cc7f34d5129770cf
