### ISSUE TITLE
Add sync progress from KOReader

### ISSUE THREAD

**Issue by CakesTwix** [Acclorite/book-story#83]
**Why you want this feature to be implemented? Please describe.**
It will be convenient to continue reading from an e-book, tablet or use as a progress backup

**Describe the feature you'd like to be implemented**
*Interface*
Login interface, domain, login, password. Login/Registration
Status, last synchronization time, sync button, when do sync(exit from book, app, etc)

**Describe alternatives you've considered**
Alternative implementation of a synchronization server, saving progress to a file and automatic import from network file systems, e.g. 

**Additional context**
Implementation server side
Official https://github.com/koreader/koreader-sync-server
Custom, python https://github.com/b1n4ryj4n/koreader-sync

**Comment by Acclorite** [comment]
The app will not focus on online, therefore no sync. I **will** provide a way to sync folders, but no sync services as far as I can say now.

**Comment by CakesTwix** [comment]
Then what about just save history.json and sync when file is updated?

**Comment by Acclorite** [comment]
I am not sure exactly what you mean, but I will provide a selective way to import/export settings
