### ISSUE TITLE
Two columns mode in reader

### ISSUE THREAD

**Issue by pzkpfw6** [Acclorite/book-story#92]
As far as I can see, the app UI is adapted for large screen (foldables and tablets) while the reader is not. A great solution for that would be two columns mode available in landscape orientation. You can see this in Moon Reader+. I would really love to see such feature in this app as it has the best UI for a e-book reader I have ever seen.

**Comment by Acclorite** [comment]
Don't think it's possible without proper pages, which is stuck at #13
