### ISSUE TITLE
some requests

### ISSUE THREAD

**Issue by asgsdbrseg** [Acclorite/book-story#99]
1.支持epub3格式。测试发现，epub3的目录、弹注、字体大小颜色都不支持。
2.支持全文搜索。静读天下、reasily、lithium都支持这点，reasily效果尤好。
3.支持左右翻页。静读天下、reasily、lithium都支持这点。
4.支持本地字体。静读天下、reasily都支持这点。
5.支持修改epub文件后实时刷新书架。静读天下、lithium都支持这点。
6.汉字选择不够精确。学习静读天下对汉字的操作。
7.选中文字后菜单只有「复制」，其他都隐藏在二级菜单中，这是不必要且浪费时间的，尤其是「词典」。
8.支持epub3弹注。静读天下、reasily、lithium都支持这点，reasily效果尤好。

**Comment by Acclorite** [comment]
Please, use [proper form of template](https://github.com/Acclorite/book-story/issues/new?assignees=Acclorite&labels=%F0%9F%9A%80+Feature+request&projects=&template=feature-request.md&title=) (and follow all checks). One more incorrect Issue and I will have to block you from sending Issues.
